import api from './api-adapter';

// Obsidian設定を取得
export const getVaultConfig = () => api.settings.get()
  .then(data => ({ data: { vaultPath: data.obsidianVaultPath || '' } }));

// Obsidian設定をチェック (互換用 - dummy)
export const checkVault = (vaultPath) => Promise.resolve({ data: { valid: true } });

// Obsidian設定を更新
export const updateVaultConfig = (data) => api.settings.save({ obsidianVaultPath: data.vaultPath })
  .then(res => ({ data: res }));

// Markdownを保存 (Google Drive Sync)
export const generateDailyNote = (data = {}) => {
  const today = new Date();
  const dateStr = today.toISOString().split('T')[0];
  const filename = `${dateStr}.md`;
  const content = `# Daily Note ${dateStr}\n\nGenerated by Dify Content Generator`;

  return api.obsidian.save(filename, content, 'Daily Notes')
    .then(res => ({ data: res }));
};

// 個別記事のNoteを生成
export const generateArticleNote = (id, templateType = 'default') => {
  // 記事情報を取得してMarkdown生成して保存するロジックが必要だが、
  // ここでは簡易的に実装するか、GAS側で実装するのが望ましい。
  // 一旦dummy
  return Promise.resolve({ data: { success: true } });
};

// Daily Notes一覧を取得 (GAS未実装 - dummy)
export const getDailyNotes = (limit = 30) => Promise.resolve({ data: [] });

export default {
  getVaultConfig,
  updateVaultConfig,
  checkVault,
  generateDailyNote,
  generateArticleNote,
  getDailyNotes
};
